---
namespace: "tcharl"
name: "kube_certmanager"
version: "1.0.1"
description: "Installs cert manager on kubernetes"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/kube_certmanager"
documentation: "https://github.com/OsgiliathEnterprise/kube_certmanager/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/kube_certmanager"
issues: "https://github.com/OsgiliathEnterprise/kube_certmanager/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "freeipa"
  - "freeipa-server"
