---

- name: Facts | retrieve current machine ip
  ansible.builtin.setup:
    gather_subset:
      - network
  register: kube_certmanager_idm_host_facts
  delegate_to: "{{ groups[idm_group] | first }}"

- name: Facts | debug preferred_nic
  ansible.builtin.debug:
    msg: "{{ idm_preferred_nic | default(omit) }}"
    verbosity: 3

- name: Facts | compute ip if preferred_nic is not set
  ansible.builtin.debug:
    msg: "{{ kube_certmanager_idm_host_facts.ansible_facts['ansible_' + idm_preferred_nic | replace('-', '_')].ipv4.address if (idm_preferred_nic is defined and not idm_preferred_nic.skipped is defined) else kube_certmanager_idm_host_facts.ansible_facts.ansible_default_ipv4.address | default(kube_certmanager_idm_host_facts.ansible_facts.ansible_all_ipv4_addresses | first) }}"
  register: kube_certmanager_ipa_current_host_ip
