---
# tasks file for ansible-users

- name: Requirements
  ansible.builtin.import_tasks: requirements.yml
  when:
    - standalone_role

#- name: Csi-volume | install cert-manager
#  kubernetes.core.helm:
#    name: cert-manager
#    chart_ref: jetstack/cert-manager
#    release_namespace: cert-manager
#    create_namespace: true
#    chart_version: v1.12.1
- name: Reference jetpack repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    kubeconfig: /root/.kube/config
  become: True

- name: Create cert-manager namespace
  kubernetes.core.k8s:
    name: cert-manager
    kind: Namespace
    state: present
    kubeconfig: /root/.kube/config
    wait_timeout: 200
    wait_sleep: 20
  register: lsresult
  until: "lsresult is not failed"
  retries: 5
  delay: 10
  become: True

- name: Deploy latest version of Certmanager
  kubernetes.core.helm:
    kubeconfig: /root/.kube/config
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    chart_version: v1.12.1
    set_values:
      - value: installCRDs=true
        value_type: string
  register: lsresult
  until: "lsresult is not failed"
  failed_when: False
  become: True