---
- name: Converge master
  hosts:
    - ipaservers
    - kube_master
  vars:
    secure_logs: False
    # preferred_nic: "eth1"
    kube_firewall_zone: 'public'
    master_preferred_nic: "eth1"
    preferred_nic: "eth1"
    reset_kube: True
    standalone_role: False
    company_domain: osgiliath.test
    company_realm_password: '123ADMin'
    company_ad_password: '123ADmPass'
    nfs_mountpoints: # Mountpoints should be configured by the tcharl.ansible_volume (nfs mounts) on the server and client side to be mounted on each node before kubernetes comes in
      - host: master.osgiliath.test
        mountpoints:
          - remote: /var/shared/csi
            local: /net
            csi_mount: Yes
          - local: /net
            remote: /var/shared/volume
            kubernetes_volumes:
              - subtree: /artefactrepo
                mountsize: 1

  roles:
    - role: tcharl.kube_certmanager
