---
dependency:
  name: galaxy
  enabled: ${DEPENDENCY_ENABLED:-True}
  options:
    role-file: ${REQUIREMENTS_PATH:-requirements-standalone.yml}
    requirements-file: requirements-collections.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: idm.osgiliath.test
    box: ${TESTBOX:-fedora-cloud-44-virtualbox}
    box_url: ${TESTBOX_URL:-https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-VirtualBox-44-1.7.x86_64.vagrant.virtualbox.box}
    provider_options:
      cpus: 2
      memory: 2048
    interfaces:
      - type: dhcp
        # ip: "192.168.56.5"
        auto_config: true
        network_name: private_network
        virtualbox__intnet: "internalnetwork"
    groups:
      - ipaservers
  - name: master.osgiliath.test
    box: ${TESTBOX:-fedora-cloud-44-virtualbox}
    box_url: ${TESTBOX_URL:-https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-VirtualBox-44-1.7.x86_64.vagrant.virtualbox.box}
    provider_options:
      cpus: 2
      memory: 2048
    interfaces:
      - type: dhcp
        # ip: "192.168.56.5"
        auto_config: true
        network_name: private_network
        virtualbox__intnet: "internalnetwork"
    groups:
      - ipaclients
      - kube_master
  - name: node1.osgiliath.test
    box: ${TESTBOX:-fedora-cloud-44-virtualbox}
    box_url: ${TESTBOX_URL:-https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-VirtualBox-44-1.7.x86_64.vagrant.virtualbox.box}
    provider_options:
      cpus: 2
      memory: 2048
    interfaces:
      - type: dhcp
        # ip: "192.168.56.5"
        auto_config: true
        network_name: private_network
        virtualbox__intnet: "internalnetwork"
    groups:
      - ipaclients
      - kube_node
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../community-collections:${HOME}/.ansible/collections:/usr/share/ansible/collections"
    ANSIBLE_VERBOSITY: 2
  config_options:
    defaults:
      remote_tmp: /tmp
      forks: 20
    ssh_connection:
      pipelining: true
      ssh_args: -4 -o ControlMaster=auto -o ControlPersist=600s
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
