---
dependency:
  name: galaxy
  enabled: ${DEPENDENCY_ENABLED:-True}
  options:
    role-file: ${REQUIREMENTS_PATH:-requirements-standalone.yml}
    requirements-file: requirements-collections.yml
driver:
  name: vagrant
  ssh_connection_options:
    - '-4'
    - '-o ControlMaster=auto'
    - '-o ControlPersist=600s'
    - '-o ConnectTimeout=60'
#    - '-o ControlPath=/tmp/m-%r@%h-%p'
    - '-o ConnectionAttempts=10'
    - '-o ServerAliveInterval=30'
    - '-o ServerAliveCountMax=5'
    - '-o TCPKeepAlive=yes'
  provider:
    name: libvirt
platforms:
  - name: idm.osgiliath.test
    box: ${TESTBOX:-fedora-cloud-44-libvirt}
    box_url: ${TESTBOX_URL:-https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-libvirt-44-1.7.x86_64.vagrant.libvirt.box}
    provider_options:
      driver: "kvm"
      cpus: 3
      memory: 4098
      qemu_use_session: false
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
        # type: static
        # ip: "192.168.50.4"
    groups:
      - ipaservers
  - name: master.osgiliath.test
    box: ${TESTBOX:-fedora-cloud-44-libvirt}
    box_url: ${TESTBOX_URL:-https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-libvirt-44-1.7.x86_64.vagrant.libvirt.box}
    provider_options:
      driver: "kvm"
      cpus: 3
      memory: 4098
      qemu_use_session: false
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
        # type: static
        # ip: "192.168.50.5"
    groups:
      - kube_master
      - ipaclients
  - name: node1.osgiliath.test
    box: ${TESTBOX:-fedora-cloud-44-libvirt}
    box_url: ${TESTBOX_URL:-https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-libvirt-44-1.7.x86_64.vagrant.libvirt.box}
    provider_options:
      driver: "kvm"
      cpus: 3
      memory: 4098
      qemu_use_session: false
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
        #type: static
        #ip: "192.168.50.6"
    groups:
      - ipaclients
      - kube_node
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../community-collections:${HOME}/.ansible/collections:/usr/share/ansible/collections"
    ANSIBLE_VERBOSITY: 2
  config_options:
    defaults:
      remote_tmp: /tmp
      forks: 20
      timeout: 30
    privilege_escalation:
      become_timeout: 60
    ssh_connection:
      pipelining: true
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: kvm
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
