---
- name: Converge master
  hosts:
    - ipaservers
    - kube_master
  vars:
    secure_logs: False
    preferred_nic: "eth1"
    idm_preferred_nic: "eth1"
    master_preferred_nic: "eth1"
    kubernetes_allow_pods_on_master: False
    kube_firewall_zone: 'public'
    standalone_role: False
    company_domain: osgiliath.test
    company_realm_password: '123ADMin'
    company_ad_password: '123ADmPass'
    reset_kube: True
    nfs_mountpoints: # Mountpoints should be configured by the tcharl.ansible_volume (nfs mounts) on the server and client side to be mounted on each node before kubernetes comes in
      - host: master.osgiliath.test
        mountpoints:
          - remote: /var/shared/csi
            local: /net
            csi_mount: Yes
#        kube_alt_names:
#          - "kubeadm.osgiliath.net"
  roles:
    - role: tcharl.kube_certmanager
